BEGIN;

CREATE SCHEMA IF NOT EXISTS "severe_weather";

CREATE TABLE IF NOT EXISTS "severe_weather".details (
	begin_yearmonth INTEGER, 
	begin_day INTEGER, 
	begin_time INTEGER, 
	end_yearmonth INTEGER, 
	end_day INTEGER, 
	end_time INTEGER, 
	episode_id INTEGER, 
	event_id INTEGER, 
	state VARCHAR, 
	state_fips INTEGER, 
	year INTEGER, 
	month_name VARCHAR, 
	event_type VARCHAR, 
	cz_type VARCHAR, 
	cz_fips INTEGER, 
	cz_name VARCHAR, 
	wfo VARCHAR, 
	begin_date_time TIMESTAMP WITHOUT TIME ZONE, 
	cz_timezone VARCHAR, 
	end_date_time TIMESTAMP WITHOUT TIME ZONE, 
	injuries_direct INTEGER, 
	injuries_indirect INTEGER, 
	deaths_direct INTEGER, 
	deaths_indirect INTEGER, 
	damage_property VARCHAR, 
	damage_crops VARCHAR, 
	source VARCHAR, 
	magnitude FLOAT, 
	magnitude_type VARCHAR, 
	flood_cause VARCHAR, 
	category VARCHAR, 
	tor_f_scale VARCHAR, 
	tor_length FLOAT, 
	tor_width FLOAT, 
	tor_other_wfo VARCHAR, 
	tor_other_cz_state VARCHAR, 
	tor_other_cz_fips VARCHAR, 
	tor_other_cz_name VARCHAR, 
	begin_range INTEGER, 
	begin_azimuth VARCHAR, 
	begin_location VARCHAR, 
	end_range INTEGER, 
	end_azimuth VARCHAR, 
	end_location VARCHAR, 
	begin_lat FLOAT, 
	begin_lon FLOAT, 
	end_lat FLOAT, 
	end_lon FLOAT, 
	episode_narrative VARCHAR, 
	event_narrative VARCHAR, 
	data_source VARCHAR
);

COMMIT;
